# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            TysonBarrett.com
tagline:          'Thinking Stats'
description:      'Any fool can know. The point is to understand. - Einstein'
url:              https://tysonstanley.github.io
baseurl:          ''
description2:     'This site is a compilation of: (1) my #rstats blog, (2) my research and teaching portfolio, and (3) information about my data science consulting company -- Thinking Stats. See the sidebar for more information.'
description3:     'I am a Data Scientist and <a href="https://twitter.com/hashtag/rstats">#rstats</a> and <a href="https://osf.io">open science</a> enthusiast. I currently work at <a href="http://www.usu.edu">Utah State University</a> as Research Assistant Professor. I serve as a methodologist on several research teams, and develop interpretable methodologies and accessible tools. This site contains my blog and other open resources for learning data analysis.'

author:
  name:           'Tyson S. Barrett'
  url:            https://twitter.com/healthandstats

paginate:         6

github:
  repo:           https://github.com/tysonstanley
twitter:          https://twitter.com/healthandstats
researchgate:     https://www.researchgate.net/profile/Tyson_Barrett
orcid:            orcid.org/0000-0002-2137-1391
furniture:        https://tysonstanley.github.io/furniture
MargMed:          https://github.com/tysonstanley/MarginalMediation
