# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            TysonBarrett.com
tagline:          'Chaos to Clarity'
description:      'Finding the clarity among the chaos of data'
url:              https://tysonstanley.github.io
baseurl:          ''
description2:     'This site contains: (1) #rstats blog, (2) my research and teaching portfolio, and (3) my data science consulting company--Thinking Stats. See the sidebar for more information.'
description3:     'Bio-behavioral Data Scientist and #Rstats Enthusiast. I am currently a researher (and PhD Candidate) at Utah State University in Quantitative Psychology. I am a statistical and data science consultant for the college. I am interested in reproducibility of research, exploratory data analysis, machine learning, and mediation analysis.'

author:
  name:           'Tyson S. Barrett'
  url:            https://twitter.com/healthandstats

paginate:         6

github:
  repo:           https://github.com/tysonstanley
twitter:          https://twitter.com/healthandstats
researchgate:     https://www.researchgate.net/profile/Tyson_Barrett
orcid:            orcid.org/0000-0002-2137-1391
