# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Chaos to Clarity in R
tagline:          ' R Made SimpleR'
description:      '#Rstats Enthusiast, Statistician, and Prevention Researcher. [**Orcid**](http://orcid.org/0000-0002-2137-1391) and [**ResearchGate**](https://www.researchgate.net/profile/Tyson_Barrett)'
url:              https://tysonstanley.github.io
baseurl:          ''

author:
  name:           'Tyson S. Barrett'
  url:            https://twitter.com/healthandstats

paginate:         6

# Custom vars
version:          1.5.1

github:
  repo:           https://github.com/tysonstanley

