# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Chaos to Clarity in R
tagline:          'Tyson S. Barrett'
description:      'Finding the clarity among the chaos of data'
url:              https://tysonstanley.github.io
baseurl:          ''

author:
  name:           'Tyson S. Barrett'
  url:            https://twitter.com/healthandstats

paginate:         6

github:
  repo:           https://github.com/tysonstanley
twitter:          https://twitter.com/healthandstats
researchgate:     https://www.researchgate.net/profile/Tyson_Barrett
orcid:            orcid.org/0000-0002-2137-1391
