---
title: "The Accuracy and Statistical Power of Average Marginal Effects"
description: "Below is a Prezi presentation I have prepared for a seminar about the accuracy and statistical power of **Average Marginal Effects** (AME's). It presents some simulations that I ran to assess the bias, the statistical power, and the CI…"
date: 2017-03-10
author: Tyson S. Barrett
categories: [regression]
---
Below is a Prezi presentation I have prepared for a seminar about the accuracy and statistical power of **Average Marginal Effects** (AME's). It presents some simulations that I ran to assess the bias, the statistical power, and the CI coverage of AME's under various conditions. Although not directly related to using `R`, the simulations were performed in `R` and we introduce two packages that allow its use. Note that the two packages (e.g., `MarginalMediation` and `margins`) are only available on *GitHub* at the present. 

Ultimately, this is going to lead to **Marginal Mediation**. We are in the midst of developing a paper to introduce Marginal Mediation and to demonstrate its usefulness in several situations.

<iframe id="iframe_container" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" width="725" height="500" src="https://prezi.com/embed/wubokjvtjgzu/?bgcolor=ffffff&amp;lock_to_path=1&amp;autoplay=0&amp;autohide_ctrls=0&amp;landing_data=bHVZZmNaNDBIWnNjdEVENDRhZDFNZGNIUE43MHdLNWpsdFJLb2ZHanI0OUhUNDh6VTJlNlVMclVGaWxpWm5nbkdnPT0&amp;landing_sign=D89xDkiTKfrBBlOcUW7BXrRmZY5MMnIlrMGUSCz0zGQ"></iframe>

I'll post again once we publish more information on average marginal effects and marginal mediation in the next few months. 

As a final note, a great paper presenting the basics of average marginal effects can be found [here](http://www.stata-journal.com/sjpdf.html?articlenum=st0086).
